version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo-furia
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: furia
      MONGO_INITDB_ROOT_PASSWORD: furia
    networks:
      - furia-network

volumes:
  mongo_data:

networks:
  furia-network:
    driver: bridge
