export const titulos = [
  {
    posicao: "1º",
    campeonato: "ESL Pro League Season 12 North America",
    resultado: "3x0",
    adversario: "100 Thieves",
    premiacao: "US$77,500",
  },
  {
    posicao: "2º",
    campeonato: "Esports Championship Series Season 7 Finals",
    resultado: "0x2",
    adversario: "Team Vitality",
    premiacao: "US$100,000",
  },
  {
    posicao: "3º–4º",
    campeonato: "Intel Extreme Masters Rio 2024",
    resultado: "0x2",
    adversario: "MOUZ",
    premiacao: "US$20,000",
  },
  {
    posicao: "3º–4º",
    campeonato: "ESL Pro League Season 13",
    resultado: "0x2",
    adversario: "Ninjas in Pyjamas",
    premiacao: "US$28,000",
  },
  {
    posicao: "3º–4º",
    campeonato: "Intel Extreme Masters Rio Major 2022",
    resultado: "1x2",
    adversario: "HEROIC",
    premiacao: "US$80,000",
  },
  {
    posicao: "3º–4º",
    campeonato: "ESL Pro League Season 15",
    resultado: "0x2",
    adversario: "FaZe Clan",
    premiacao: "US$55,000",
  },
  {
    posicao: "3º–4º",
    campeonato: "DreamHack Masters Dallas 2019",
    resultado: "0x2",
    adversario: "Team Liquid",
    premiacao: "US$22,000",
  },
  {
    posicao: "3º–4º",
    campeonato: "ESL One: Cologne 2020 Online - North America",
    resultado: "0x2",
    adversario: "Evil Genuises",
    premiacao: "US$12,500",
  },
  {
    posicao: "3º–4º",
    campeonato: "Intel Extreme Masters Season XVII - Dallas",
    resultado: "0x2",
    adversario: "ENCE",
    premiacao: "US$22,000",
  },
];
